package com.mani.compiler;

import com.mani.lang.Mani;

import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
public class ManiCompiler {

    public static void main(String[] args) {
        // This is where we go through the internal resources folder.
        // Inside that there will be a settings file (Generated by Mani itself)
        // It will determine what file is to be executed first (Mani file)

        Mani.compiledMode = true;
        Mani.hasInternet = true; // To make it completely un-needed to have mani installed.

        ClassLoader classLoader = ManiCompiler.class.getClassLoader();
        File file = new File(classLoader.getResource("main.mn").getFile());
        try {
            byte[] bytes = Files.readAllBytes(file.toPath());
            Mani.run(new String(bytes, Charset.defaultCharset()));
        } catch(IOException e) {
            e.printStackTrace();
        }
    }
}